{% set version = "0.5.2" %}

package:
  name: conda_envfile
  version: {{ version }}

source:
  url: https://github.com/tdegeus/conda_envfile/archive/v{{ version }}.tar.gz
  sha256: a4a88d12b17dcada8fc9e56744aaf39a739307ccfa58dbf781ca0c5108d3aac0

build:
  number: 0
  noarch: python
  script_env: SETUPTOOLS_SCM_PRETEND_VERSION={{ version }}
  script: {{ PYTHON }} -m pip install . -vv
  entry_points:
    - conda_envfile_diff = conda_envfile:_conda_envfile_diff_cli
    - conda_envfile_merge = conda_envfile:_conda_envfile_merge_cli
    - conda_envfile_parse = conda_envfile:_conda_envfile_parse_cli
    - conda_envfile_pyproject = conda_envfile:_conda_envfile_pyproject_cli
    - conda_envfile_restrict = conda_envfile:_conda_envfile_restrict_cli

requirements:
  host:
    - pip
    - python >=3.11
    - setuptools_scm
  run:
    - click
    - jinja2
    - packaging
    - prettytable
    - python >=3.11
    - pyyaml

test:
  requires:
    - pip
  imports:
    - conda_envfile
  commands:
    - pip check
    - python -c "import conda_envfile; assert conda_envfile.version == '{{ version }}'"
    - conda_envfile_diff --version | grep {{ version }}
    - conda_envfile_merge --version | grep {{ version }}
    - conda_envfile_parse --version | grep {{ version }}
    - conda_envfile_pyproject --version | grep {{ version }}
    - conda_envfile_restrict --version | grep {{ version }}

about:
  home: https://github.com/tdegeus/conda_envfile
  license: MIT
  license_family: MIT
  license_file: LICENSE
  summary: Simple command-line tools to clean / merge conda environment files.
  description: Simple command-line tools to clean / merge conda environment files.
  doc_url: https://conda_envfile.readthedocs.io/
  dev_url: https://github.com/tdegeus/conda_envfile

extra:
  recipe-maintainers:
    - tdegeus
